'use client';
import {useEffect,useRef,useState} from 'react';
import {ZoomIn,ZoomOut,X,RotateCcw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
export function ResearchImage({src,alt='',number}:{src?:string;alt?:string;number?:number}){
 const[loaded,setLoaded]=useState(true),[failed,setFailed]=useState(false),[open,setOpen]=useState(false),[zoom,setZoom]=useState(1),[play,setPlay]=useState(false);const image=useRef<HTMLImageElement>(null);
 const animated=!!src&&/\.(gif|apng)(?:[?#]|$)/i.test(src);const caption=alt.replace(/\s*\|\s*来源[:：].*$/,'');const source=alt.match(/\|\s*来源[:：]\s*(https?:\/\/\S+)/)?.[1];
 useEffect(()=>{setFailed(false);setLoaded(!!image.current?.complete&&!!image.current?.naturalWidth)},[src]);
 return <figure className="research-figure">{animated&&!play?<button className="button" onClick={()=>setPlay(true)}>点击播放动画</button>:failed?<div className="image-error" role="status">图片未能加载。{src&&<a href={src} target="_blank" rel="noreferrer">查看原图</a>}</div>:<button className={'image-button '+(!loaded?'is-loading':'')} aria-label={'放大图片：'+(caption||'正文图片')} onClick={()=>{setZoom(1);setOpen(true)}}><img ref={image} src={src} alt={caption} loading="lazy" onLoad={()=>setLoaded(true)} onError={()=>{setLoaded(true);setFailed(true)}}/></button>}{(caption||source||number)&&<figcaption>{number?('图 '+number+' · '):''}{caption}{source&&<> · 来源：<a href={source} target="_blank" rel="noreferrer">原始资料</a></>}</figcaption>}
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="image-viewer" showCloseButton={false} onKeyDown={e=>{if(e.key==='+'||e.key==='=')setZoom(z=>Math.min(4,z+.25));if(e.key==='-')setZoom(z=>Math.max(.5,z-.25))}}><div className="image-viewer-toolbar"><DialogTitle>{caption||'图片查看器'}</DialogTitle><div><button className="button" aria-label="缩小图片" onClick={()=>setZoom(z=>Math.max(.5,z-.25))}><ZoomOut/></button><span aria-live="polite">{Math.round(zoom*100)}%</span><button className="button" aria-label="放大图片" onClick={()=>setZoom(z=>Math.min(4,z+.25))}><ZoomIn/></button><button className="button" aria-label="重置缩放" onClick={()=>setZoom(1)}><RotateCcw/></button><DialogClose asChild><button className="button" aria-label="关闭图片"><X/>关闭</button></DialogClose></div></div><DialogDescription>使用加减按钮缩放，滚动查看细节，按 Esc 关闭。</DialogDescription><div className="image-viewport" tabIndex={0} role="region" aria-label="放大图片滚动区域"><div className="image-zoom-canvas" style={{width:Math.max(1,zoom)*100+'%'}}><img src={src} alt={caption} style={{width:zoom<1?zoom*100+'%':'100%'}}/></div></div></DialogContent></Dialog></figure>
}

